export { HomePage } from "./home";
export { EmployeePage ,UserDetailPage } from "./employee";
export { LeadPage} from "./lead";
export { BatchPage ,BatchDetail} from "./batch";
export { PageNotFoundPage } from "./pageNotFound";
export { CandidatePage , CandidateDetailPage} from "./candidate";
export { SessionclassListPage ,SessionclassDetailPage } from "./sessionclass";
export { TrainerLoginPage ,WhoIAmPage ,CandidateLoginPage } from "./auth";
export { AtQuizPage } from "./atQuiz";
export { ProfilePage } from "./profile";
